USE [master]
GO

/****** Object:  Database [OrtInterviewDatabase]    Script Date: 12/07/2023 18:02:46 ******/
CREATE DATABASE [OrtInterviewDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OrtInterviewDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\OrtInterviewDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OrtInterviewDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\OrtInterviewDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OrtInterviewDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OrtInterviewDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OrtInterviewDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OrtInterviewDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OrtInterviewDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OrtInterviewDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [OrtInterviewDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [OrtInterviewDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OrtInterviewDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OrtInterviewDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OrtInterviewDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OrtInterviewDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OrtInterviewDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [OrtInterviewDatabase] SET QUERY_STORE = ON
GO

ALTER DATABASE [OrtInterviewDatabase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [OrtInterviewDatabase] SET  READ_WRITE 
GO


